# Generated by Django 5.1.7 on 2025-03-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
