# Generated by Django 5.1.7 on 2025-03-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='old_cart',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
