# Generated by Django 5.1.7 on 2025-03-31 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='old_cart',
        ),
    ]
